# Directory: commons_care_analytics/
# File: app.py

import streamlit as st
from src.sections import health_outcome, financial_risk_protection, access
from streamlit_extras.stylable_container import stylable_container

st.set_page_config(layout="wide")

# --- Load Custom CSS ---
with open(".streamlit/style.css") as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

# --- Initialize Session State ---
if "selected_goal" not in st.session_state:
    st.session_state.selected_goal = "Access"

# --- Main Layout ---
with st.container(key="system_goal_selector"):
    st.markdown("#### Select System Goal")
    b1, _, b2, _, b3 = st.columns([1, 0.025, 1, 0.025, 1])
    with b1:
        if st.button(
            "Health Outcomes",
            use_container_width=True,
            # key=(
            #     "selected_button"
            #     if st.session_state.selected_goal == "Health Outcome"
            #     else None
            # ),
        ):
            st.session_state.selected_goal = "Health Outcome"
    with b2:
        st.button(
            "Customer Satisfactions",
            disabled=True,
            use_container_width=True,
            # key=(
            #     "selected_button"
            #     if st.session_state.selected_goal == "Customer Satisfaction"
            #     else None
            # ),
        )
    with b3:
        if st.button(
            "Financial Risk Protections",
            use_container_width=True,
            # key=(
            #     "selected_button"
            #     if st.session_state.selected_goal == "Financial Risk Protection"
            #     else None
            # ),
        ):
            st.session_state.selected_goal = "Financial Risk Protection"

# col1: Intermediate Goals
# col_div1: Divider Between col1 and col2
# col2: System Goal Selector
# col_div2: Divider Between col2 and col3
# col3: AI Insights Panel
col1, col_div1, col2, col_div2, col3 = st.columns([0.8, 0.05, 3, 0.05, 1])

# --- Intermediate Goals ---
with col1:
    with st.container(key="intermediate_card"):
        st.markdown("#### Intermediate Goals")
        if st.button("Access", use_container_width=True):
            st.session_state.selected_goal = "Access"
        st.button("Quality", disabled=True, use_container_width=True)
        st.button("Efficiency", disabled=True, use_container_width=True)
        st.button("Equity", disabled=True, use_container_width=True)


# --- Main Section Render (after AI panel setup) ---
with col2:
    if st.session_state.selected_goal == "Health Outcome":
        health_outcome.render_new()
    elif st.session_state.selected_goal == "Financial Risk Protection":
        financial_risk_protection.render_new()
    elif st.session_state.selected_goal == "Access":
        access.render_new()

    # --- Control Knobs ---
    with st.container(key="control_knob_container"):
        st.markdown(
            """
            <h4>Control Knobs</h4>
            <p>Use these knobs to adjust the parameters of the model.</p>
            """,
            unsafe_allow_html=True,
        )
        knob_cols = st.columns(5)
        for col, label in zip(
            knob_cols,
            ["Financing", "Behavior", "Organization", "Regulation", "Payment"],
        ):
            with col:
                st.button(
                    label,
                    disabled=True,
                    help="Feature coming soon",
                    use_container_width=True,
                )


# --- AI Insights Panel ---
with col3:
    if st.session_state.selected_goal == "Health Outcome":
        health_outcome.render_insight_new()
    elif st.session_state.selected_goal == "Financial Risk Protection":
        financial_risk_protection.render_insight()
    else:
        st.markdown(
            f"""
        <div class="insight-card">
            <h4>💡 Commons-Care Insights </h4>
            <div class="panel-message">
                This panel provides data-driven summaries generated by AI.
            </div>
            <div class="panel-footer">
                Generated by Commons-Care AI
            </div>
        </div>
        """,
            unsafe_allow_html=True,
        )
