# Directory: commons_care_analytics/
# File: app.py

import streamlit as st
from src.sections import health_outcome, financial_risk_protection, access

st.set_page_config(layout="wide")

# --- Load Custom CSS ---
with open(".streamlit/style.css") as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

# --- Initialize Session State ---
if "selected_goal" not in st.session_state:
    st.session_state.selected_goal = "Access"

# --- Main Layout ---
st.title("System Goals Dashboard")
st.markdown("---")

col1, col_div1, col2, col_div2, col3 = st.columns([0.7, 0.05, 3, 0.05, 1])

# --- Intermediate Goals ---
with col1:
    st.markdown("#### Intermediate Goals")
    if st.button("Access", use_container_width=True):
        st.session_state.selected_goal = "Access"
    st.button("Quality", disabled=True, use_container_width=True)
    st.button("Efficiency", disabled=True, use_container_width=True)
    st.button("Equity", disabled=True, use_container_width=True)

with col_div1:
    st.markdown(
        """<div style='height: 320px; border-left: 1px solid #ccc;'></div>""",
        unsafe_allow_html=True,
    )

# --- System Goal Selector ---
with col2:
    st.markdown("#### Select System Goal")
    b1, _, b2, _, b3 = st.columns([1, 0.025, 1, 0.025, 1])
    with b1:
        if st.button("Health Outcome", use_container_width=True):
            st.session_state.selected_goal = "Health Outcome"
    with b2:
        st.button("Customer Satisfaction", disabled=True, use_container_width=True)
    with b3:
        if st.button("Financial Risk Protection", use_container_width=True):
            st.session_state.selected_goal = "Financial Risk Protection"

    st.markdown("---")
    st.markdown(f"**Current View:** `{st.session_state.selected_goal}`")

with col_div2:
    st.markdown(
        """<div style='height: 320px; border-left: 1px solid #ccc;'></div>""",
        unsafe_allow_html=True,
    )

# --- Main Section Render (after AI panel setup) ---
with col2:
    if st.session_state.selected_goal == "Health Outcome":
        health_outcome.render()
    elif st.session_state.selected_goal == "Financial Risk Protection":
        financial_risk_protection.render()
    elif st.session_state.selected_goal == "Access":
        access.render()

# --- AI Insights Panel ---
with col3:
    st.markdown("#### Commons-Care Insights")
    if st.session_state.selected_goal == "Health Outcome":
        health_outcome.render_insight()
    elif st.session_state.selected_goal == "Financial Risk Protection":
        financial_risk_protection.render_insight()
    st.info("This panel provides data-driven summaries generated by AI.")
    st.caption("Generated by Commons-Care AI")

# --- Control Knobs ---
st.markdown("---")
knob_cols = st.columns(5)
for col, label in zip(
    knob_cols, ["Financing", "Behavior", "Organization", "Regulation", "Payment"]
):
    with col:
        st.button(
            label, disabled=True, help="Feature coming soon", use_container_width=True
        )

st.markdown(
    "<h4 style='text-align: center;'>Control Knobs</h4>", unsafe_allow_html=True
)
